name: Run tests

on:
  push:
  schedule:
      - cron: '0 0 * * *'

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [7.4, 7.3, 7.2]
                laravel: [6.*, 7.*]
                os: [ubuntu-latest]
                include:
                    - laravel: 6.*
                      testbench: 4.*
                    - laravel: 7.*
                      testbench: 5.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  extension: pdo, sqlite, pdo_sqlite
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --prefer-dist --prefer-dist --no-interaction --no-suggest

            - name: Info
              run: composer show

            - name: Execute tests
              run: composer test
